#!/usr/bin/env node
/*
  Regenerates src/components/site/Logo.tsx from public/brand/logo.svg.

  Hand-transcribing 20KB of path data is how typos ship. Run this after any
  change to the source logo. The logo is used exactly as supplied — only
  animated, never redrawn.

  Every letter keeps its id and data-letter attribute, because the loader and
  the footer address individual letters by id to draw and flood them.
*/
import { readFileSync, writeFileSync } from "node:fs";

const svg = readFileSync("public/brand/logo.svg", "utf8");

const paths = [...svg.matchAll(/<path\b([^>]*?)\/>/gs)].map(([, attrs]) => {
  // The leading (^|\s) matters: without it, `d="..."` matches inside
  // `id="top-w"` and every letter silently gets an invalid path.
  const get = (n) =>
    (attrs.match(new RegExp(`(?:^|\\s)${n}="([^"]*)"`, "s")) || [])[1];
  return { id: get("id"), letter: get("data-letter"), d: get("d") };
});

if (paths.length !== 12) {
  throw new Error(`expected 12 letter paths, found ${paths.length}`);
}
for (const p of paths) {
  if (!p.id || !p.letter || !p.d) {
    throw new Error(`path missing id/data-letter/d: ${JSON.stringify(p)}`);
  }
}

const groupOf = (id) => (id.startsWith("top-") ? "we-code" : "coders");

const render = (group) =>
  paths
    .filter((p) => groupOf(p.id) === group)
    .map(
      (p) =>
        `        <path\n` +
        `          id={\`\${idPrefix}-${p.id}\`}\n` +
        `          className="logo-letter"\n` +
        `          data-letter="${p.letter}"\n` +
        `          fill={fill}\n` +
        `          fillRule="evenodd"\n` +
        `          clipRule="evenodd"\n` +
        `          d="${p.d}"\n` +
        `        />`,
    )
    .join("\n");

const out = `// GENERATED by scripts/gen-logo.mjs — do not edit by hand.
// Regenerate with: node scripts/gen-logo.mjs

import type { CSSProperties } from "react";

type LogoProps = {
  className?: string;
  /** Namespaces the gradient and letter ids so two Logos on one page do not collide. */
  idPrefix?: string;
  title?: string;
  /** Hides the mark from assistive tech when it is purely decorative. */
  decorative?: boolean;
  style?: CSSProperties;
  /**
   * The wordmark's own pink gradient is built for a violet ground and is
   * effectively invisible on cream. Use "brand" on violet or ink; use "ink"
   * or "current" wherever the mark sits on paper.
   */
  tone?: "brand" | "ink" | "paper" | "current";
};

const FILL: Record<NonNullable<LogoProps["tone"]>, (p: string) => string> = {
  brand: (p) => \`url(#\${p}-gradient)\`,
  ink: () => "var(--color-ink)",
  paper: () => "var(--color-paper)",
  current: () => "currentColor",
};

export function Logo({
  className,
  idPrefix = "logo",
  title = "We Code Coders",
  decorative = false,
  tone = "brand",
  style,
}: LogoProps) {
  const fill = FILL[tone](idPrefix);

  return (
    <svg
      className={className}
      style={style}
      viewBox="0 0 1328 884"
      {...(decorative
        ? { "aria-hidden": true as const, role: "presentation" }
        : { role: "img" as const, "aria-label": title })}
    >
      <defs>
        <linearGradient id={\`\${idPrefix}-gradient\`} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#FFD0DC" />
          <stop offset="0.52" stopColor="#F9C1D0" />
          <stop offset="1" stopColor="#F2B1C4" />
        </linearGradient>
      </defs>
      <g id={\`\${idPrefix}-we-code\`}>
${render("we-code")}
      </g>
      <g id={\`\${idPrefix}-coders\`}>
${render("coders")}
      </g>
    </svg>
  );
}
`;

writeFileSync("src/components/site/Logo.tsx", out);
console.log(`gen-logo: wrote ${paths.length} letter paths`);
